

# This file was *autogenerated* from the file /home/gokul/Documents/mm2090_assignment/assignment5/q2/q2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_14 = Integer(14); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0p5 = RealNumber('0.5')
def pltcircles(p,r):
    g=Graphics()
    title="p={}    r={}".format(p,r)
    g+=text(title,(_sage_const_0 ,_sage_const_7 ))
    for n in srange(_sage_const_0 , _sage_const_2 *math.pi+math.pi/_sage_const_14 , math.pi/_sage_const_14 ):
        g+=circle(((p)*(math.sin(n)), (p)*math.cos(n)),r,rgbcolor=hue(n))
    g.show(xmin=-_sage_const_8 ,ymin=-_sage_const_8 ,xmax=_sage_const_8 ,ymax=_sage_const_8 )
from sage.repl.ipython_kernel.interact import sage_interactive
sage_interactive(pltcircles,p=(_sage_const_1 ,_sage_const_3 ,_sage_const_0p5 ),r=(_sage_const_1 ,_sage_const_3 ,_sage_const_0p5 ))

